# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WallPaper-CoreData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WallPaper-CoreData

end

target 'Wallpaper-WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wallpaper-WidgetExtension

end
