# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def shared_pods
	#pod 'RealmSwift' 
end
target 'WallPaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
shared_pods
  # Pods for WallPaper

end

target 'Wallpaper-WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
shared_pods
  # Pods for Wallpaper-WidgetExtension

end
